[BT-2] Implement core project
M-Vitalii/BillTrack pull request #3
Opened 2024-08-13 10:48 UTC by M-Vitalii

# Description
Implemented Core project

### What's added:
- Contracts
- Mapping
- Validation
- Interfaces for service and repository layer

2024-08-13 12:05 UTC, PIoneer2 requested changes
Please, remove IGenericService and the typed services.
For now, create 3 services. 1 service for each of our applications.

2024-08-13 12:05 UTC, PIoneer2 commented on BillTrack.Core/Interfaces/Services/IDepartmentService.cs
> +public interface IDepartmentService : IGenericService<DepartmentResponse, DepartmentRequest>
Typed services are not required. Services are for business logic. They include repo operations and more. They can operate with any incoming or outgoing objects.
This project can have just a few non-typed services. Each of them will have operations with different entities.

2024-08-13 12:05 UTC, PIoneer2 commented on BillTrack.Core/Interfaces/Services/IGenericService.cs
> +public interface IGenericService<TResponse, in TRequest>
There is IGenericRepository to handle with Entities. Also, services are not typed. Then such a generic service is not required either.

2024-08-14 12:51 UTC, M-Vitalii commented on BillTrack.Core/Interfaces/Services/IDepartmentService.cs
> +public interface IDepartmentService : IGenericService<DepartmentResponse, DepartmentRequest>
fixed

2024-08-14 12:51 UTC, M-Vitalii commented on BillTrack.Core/Interfaces/Services/IGenericService.cs
> +public interface IGenericService<TResponse, in TRequest>
fixed

2024-08-14 12:53 UTC, M-Vitalii commented
The validation will be transferred to the Web Api project when the task “Implement the Web Api project” starts.

2024-08-14 13:48 UTC, PIoneer2 approved these changes
implement bases for the Core project.
OK.

2024-08-14 16:05 UTC, merged