[BT-6] Implement worker project
M-Vitalii/BillTrack pull request #7
Opened 2024-09-11 13:16 UTC by M-Vitalii

# Description
Implemented Worker project and was successfully integrated with AWS services

### What's new:
- Web api with aws lambda support
- Generating pdf
- publishing messages to queue
- triggering lambda and receiving messages from aws sqs
- uploading generated pdf to s3 bucket
- updating invoice with generated pdf s3 url

2024-09-12 10:02 UTC, PIoneer2 requested changes
There are a lot of comments. Most of them are recommendations.
But not about BillTrack.Worker/Services/PdfUploader.cs. It requires an update to perform upload only. Work with DB should be separated.

Please, extract and execute the work with the DB after the file uploading.

2024-09-12 10:02 UTC, PIoneer2 commented on BillTrack.Api/Features/Invoices/Endpoints/CreateInvoice.cs
> +        _logger = logger;
is `_logger` in use in this endpoint?
If not - please, remove.

2024-09-12 10:02 UTC, PIoneer2 commented on BillTrack.Api/Features/Invoices/Endpoints/CreateInvoice.cs
> +        _configuration = configuration;
please, move queue work to `_webApiService`.

2024-09-12 10:02 UTC, PIoneer2 commented on BillTrack.Api/Features/Invoices/Endpoints/CreateInvoice.cs
> +            });
publishing to queue is a part of an invoice creation logic. Please, move the interaction with the queue to `_webApiService`.

2024-09-12 10:02 UTC, PIoneer2 commented on BillTrack.Api/Program.cs
> +builder.Services.AddAWSLambdaHosting(LambdaEventSource.HttpApi);
to allow local run for tests we can make it optional:
```suggestion
if (!OpEnvironment.IsLocal)
{
  builder.Services.AddAWSLambdaHosting(LambdaEventSource.HttpApi);
}
```

2024-09-12 10:02 UTC, PIoneer2 commented on BillTrack.Application/Services/SqsPublisher.cs
> +    public async Task PublishAsync<T>(string queueName, T message)
a generic implementation. It could be good for a big project. For a small project, each time queue URL resolution could be time-consuming. There is a point in building the URL elsewhere (decouple this functionality). Or cache the result inside the `SqsPublisher` - have a dictionary/map, that will store the "name - URL" mapping.

`PublishAsync<T>(string queueName, T message)`, probably, could be made shorter: `PublishAsync(string queueName, object message)`.

2024-09-12 10:02 UTC, PIoneer2 commented on BillTrack.Core/Interfaces/Services/IPdfUploader.cs
> +public interface IPdfUploader
the functionality could be used not only for PDFs. For any file. So we can omit the PDF reference in the naming. It more looks like "IFileUploader".

2024-09-12 10:02 UTC, PIoneer2 commented on BillTrack.Core/Interfaces/Services/IPdfUploader.cs
> +    Task UploadPdfToS3(Stream pdfStream, string bucketName, string fileName, Guid invoiceId);
the same about PDF in the naming. It more looks like "UploadFileToS3".

2024-09-12 10:02 UTC, PIoneer2 commented on BillTrack.Worker/Function.cs
> +            string bucketName = Environment.GetEnvironmentVariable("BucketName");
this is a static variable during the function work. It could be initialized once during constructor work.

2024-09-12 10:02 UTC, PIoneer2 commented on BillTrack.Worker/Function.cs
> +            await _pdfUploader.UploadPdfToS3(pdfStream, bucketName, fileName, invoice.InvoiceId);
Do you know if we need loggering here?

PDF generation could crash. Upload to S3 - also can fail. Do we need `try ... catch...` clauses here?

2024-09-12 10:02 UTC, PIoneer2 commented on BillTrack.Worker/Readme.md
Please, add something to this file.
At least, what purpose has this project.

2024-09-12 10:02 UTC, PIoneer2 commented on BillTrack.Worker/Services/PdfUploader.cs
> +        var region = Environment.GetEnvironmentVariable("AWS_REGION");
also a static variable. It could be initialized once on the BillTrack.Worker/Function.cs startup.

2024-09-12 10:02 UTC, PIoneer2 commented on BillTrack.Worker/Services/PdfUploader.cs
> +        _invoiceRepository = invoiceRepository;
Uploader should just "upload". So DB interaction (repository) doesn't fit by semantics and by the "single responsibility" principle.

Please, move the repo out of this service to BillTrack.Worker/Function.cs. It will be the next step after `await _pdfUploader.UploadPdfToS3(pdfStream, bucketName, fileName, invoice.InvoiceId);`. Just return the file path from the `UploadPdfToS3`/UploadFileToS3 method.

2024-09-18 15:37 UTC, M-Vitalii commented on BillTrack.Api/Features/Invoices/Endpoints/CreateInvoice.cs
> +        _logger = logger;
fixed

2024-09-18 15:37 UTC, M-Vitalii commented on BillTrack.Api/Features/Invoices/Endpoints/CreateInvoice.cs
> +        _configuration = configuration;
fixed

2024-09-18 15:38 UTC, M-Vitalii commented on BillTrack.Api/Features/Invoices/Endpoints/CreateInvoice.cs
> +            });
fixed

2024-09-18 15:38 UTC, M-Vitalii commented on BillTrack.Api/Program.cs
> +builder.Services.AddAWSLambdaHosting(LambdaEventSource.HttpApi);
fixed

2024-09-18 15:38 UTC, M-Vitalii commented on BillTrack.Application/Services/SqsPublisher.cs
> +    public async Task PublishAsync<T>(string queueName, T message)
fixed

2024-09-18 15:38 UTC, M-Vitalii commented on BillTrack.Core/Interfaces/Services/IPdfUploader.cs
> +public interface IPdfUploader
fixed

2024-09-18 15:38 UTC, M-Vitalii commented on BillTrack.Core/Interfaces/Services/IPdfUploader.cs
> +    Task UploadPdfToS3(Stream pdfStream, string bucketName, string fileName, Guid invoiceId);
fixed

2024-09-18 15:38 UTC, M-Vitalii commented on BillTrack.Worker/Function.cs
> +            string bucketName = Environment.GetEnvironmentVariable("BucketName");
fixed

2024-09-18 15:39 UTC, M-Vitalii commented on BillTrack.Worker/Function.cs
> +            await _pdfUploader.UploadPdfToS3(pdfStream, bucketName, fileName, invoice.InvoiceId);
fixed

2024-09-18 15:39 UTC, M-Vitalii commented on BillTrack.Worker/Services/PdfUploader.cs
> +        var region = Environment.GetEnvironmentVariable("AWS_REGION");
fixed

2024-09-18 15:39 UTC, M-Vitalii commented on BillTrack.Worker/Services/PdfUploader.cs
> +        _invoiceRepository = invoiceRepository;
fixed

2024-09-19 09:12 UTC, PIoneer2 commented on BillTrack.Api/Features/Invoices/Endpoints/CreateInvoice.cs
> +        await _webApiService.PublishSqsMessageAsync(message);
since this function has the queue address inbuilt - it relates only to that queue. There is a point to reflect the queue connection in its name. For example, "PublishSqsMessageWorkerAsync()".

2024-09-19 09:12 UTC, PIoneer2 commented on BillTrack.Application/Services/SqsPublisher.cs
> +    private readonly IMemoryCache _memoryCache;
`MemoryCache` functionality is much bigger than should be used here. It is redundant in this case. A simple dictionary could be used.
But it could be used for educational purposes. Then there should be comments about it.

2024-09-19 09:12 UTC, PIoneer2 commented on BillTrack.Application/Services/SqsPublisher.cs
> +        var queueName = _configuration.GetValue<string>("QueueName");
the queue's name is static. This functionality could be moved to the constructor either. The same as the queue's URL.
```suggestion
private readonly string _workerQueueName;
private string _workerQueueUrl;

public SqsPublisher(IAmazonSQS sqs, IMemoryCache memoryCache, IConfiguration configuration)
{
    _sqs = sqs;
    _workerQueueName = configuration.GetValue<string>("QueueName");
}
...
public async Task<string> GetWorkerQueueUrl()
{
    //init & cache if none was initialized before
    if (null == _workerQueueUrl)
    {
        var getQueueUrlWorkerResponse = await _sqs.GetQueueUrlAsync(_workerQueueName);
        _workerQueueUrl = getQueueUrlWorkerResponse.QueueUrl;
    }
    
    //return the cached value
    return _workerQueueUrl;
}
```

2024-09-19 09:12 UTC, PIoneer2 commented on BillTrack.Application/Services/WebApiService.cs
> +    public async Task PublishSqsMessageAsync<T>(T message)
yes, SQS can take any message type. But C# is a typed language. There is a point in adhering to the rule "one queue - one class". The Worker's queue will have the related type. From one standpoint, it is an additional architectural burden. From another one, it is an in-code type checker, a guard rail, that will verify your code and type for compatibility during development.
Making the method generic shortens the code but creates a base for future problems. A kind of "technical debt" that could cover your project in the future. There is a point in the debt creation only in exceptional cases.

2024-09-19 09:12 UTC, PIoneer2 commented on BillTrack.Worker/Function.cs
> +        services.AddTransient<IFileGenerator, InvoicePdfGenerator>();
a general named `IFileGenerator` implemented by `InvoicePdfGenerator`? Not logical. Files could be any type and content. When invoices could be implemented as different types. The name should be related to its content. The interface could keep `IInvoicePdfGenerator` name.

2024-09-19 09:12 UTC, PIoneer2 commented on BillTrack.Worker/Services/EmployeeSalaryCalculator.cs
> +        var maxPossibleHours = weekdaysInMonth * 8;
it is not the max value. The max one is `weekdaysInMonth * 24`. This one is `defaultWorkHours`. ;)

2024-09-19 09:12 UTC, PIoneer2 commented on BillTrack.Worker/Services/EmployeeSalaryCalculator.cs
> +        var calculatedSalary = hourlyRate * totalHoursWorked;
we need to ensure that the payment value is rounded up to cents according to logic controlled by us. And, maybe, the value is calculated as cents.
Different countries use different rounding logic for financial calculations. Databases can do this in a different way. Then we should handle it explicitly.

2024-09-19 09:12 UTC, PIoneer2 commented on BillTrack.Worker/Function.cs
> +            var pdfStream = await _fileGenerator.GenerateFile(invoice.InvoiceId);
`GenerateFile()` sounds like a void method that creates a file. But when we get a Stream and it is a PDF inside the method naming should reflect it. Stream is another type than File. More appropriate is `GetPdfFileStream()`.

2024-09-19 09:12 UTC, PIoneer2 commented on BillTrack.Worker/Function.cs
> +                    "Failed to upload PDF for InvoiceId: {InvoiceId} with sqs message: {@SqsMessage}",
there is a point in storing all request data in logs. But not in this way.
This way will generate tons of unique error messages. They will be hard to group. But all same errors should have something to be grouped in the same group.
It is better to keep the error message static AND log other data in additional fields.
Maybe, Serilog's `ForContext()` could handle it before `Log.Logger.Error`:
```
Log.Logger.ForContext("InvoiceId", invoice.InvoiceId);
Log.Logger.ForContext("SqsMessage", message);
Log.Logger.Error(...);
```
But Serilog has its own "enrichers" for it that should be dug.
Probably, it should be something like this:
```
//Logger creation
... logger = new LoggerConfiguration()
    .Enrich.FromLogContext()

//then in a code scope:
Serilog.Context.LogContext.PushProperty("InvoiceId", invoice.InvoiceId);
```

2024-09-19 09:12 UTC, PIoneer2 commented on BillTrack.Worker/Services/InvoicePdfUploader.cs
> +public class InvoicePdfUploader : IFileUploader
yes, this service is for "uploading". An invoice could be any file type. The type should be a specific method (function takes and returns exact types).
This name is closer to "InvoiceUploader". Its methods will handle "where upload"/"what service should be used for an upload", file types for each upload.

2024-09-19 09:12 UTC, PIoneer2 commented on BillTrack.Worker/Services/InvoicePdfUploader.cs
> +    public async Task UploadFileToS3(Stream pdfStream, string bucketName, string fileName, Guid invoiceId)
... when this method targets S3 and PDFs. Then it could be "UploadPdfToS3".
Is `Guid invoiceId` in use here?

2024-09-20 14:29 UTC, PIoneer2 commented on BillTrack.Application/Services/SqsPublisher.cs
> +        if (!_cachedQueueUrl.TryGetValue(queueName, out var queueUrl))
FYI. `out ...` initializers are not obvious to read in most cases. Yes, there are cases when there is no other way than to use this kind of initializer. Also, up to .NET v8 such initialization works much slower than a regular one.

2024-09-20 14:29 UTC, PIoneer2 commented on BillTrack.Core/Contracts/SqsMessages/CreatedInvoice.cs
> +    public string MessageType => nameof(CreatedInvoice);
please, add comments in code and reference its relation with BillTrack.Application/Services/SqsMessageDispatcher.cs - for what purpose it was implemented and what it provides?

2024-09-20 15:07 UTC, PIoneer2 approved these changes

2024-09-27 12:16 UTC, PIoneer2 approved these changes
add Update processing.
OK.

2024-10-02 08:17 UTC, merged